name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Create Gradle wrapper files
        run: |
          echo "include ':app:JCVTraductorapp'" > settings.gradle
          echo "rootProject.name='JCVTRADUCTOR'" >> settings.gradle
          cat settings.gradle
          ls -R app/JCVTraductorapp/
      - name: Build APK
        run: |
          cd app/JCVTraductorapp
          gradle wrapper
         ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: JCV-Traductor-APK
          path: app/JCVTraductorapp/build/outputs/apk/debug/*.apk
